- CQL_Guide/x4.md
- sources/sem.c
- sources/test/sem_test.err.ref
- sources/test/sem_test.out.ref
- sources/test/sem_test.sql
When using a shared fragment as an expression, the fragment should not contain calls to other shared fragments that take arguments. This is a rare case, but it's possible to declare a fragment like this:
```sql
@attribute(cql:shared_fragment)
create proc frag_example(a int not null)
begin
select (
select f.col from (call inner_frag(*))
);
end;
```
While this is a valid fragment, it shouldn't be usable as an expression fragment even though it satisfies the [restrictions outlined in the docs](https://github.com/ricomariani/CG-SQL-author/blob/main/CQL_Guide/ch14.md#restrictions).
Within a fragment used as a expression, all arguments need to come within the sql context (an expression fragment expands into a inner select statement for a select column), but arguments for normal fragments are …
> Expression fragments cannot contain nested fragments that take arguments

- sources/cqlrt_common.c
I was getting those errors:
```sh
cc -I./ -Iout -g -Werror -c cqlrt.c -o out/cqlrt.o
In file included from cqlrt.c:400:
./cqlrt_common.c:4298:47: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
static void _stub_udf_callback(sqlite3_context* context, int argc, sqlite3_value** argv)
^
./cqlrt_common.c:4298:47: note: insert '_Nullable' if the pointer may be null
static void _stub_udf_callback(sqlite3_context* context, int argc, sqlite3_value** argv)
^
_Nullable
./cqlrt_common.c:4298:47: note: insert '_Nonnull' if the pointer should never be null
static void _stub_udf_callback(sqlite3_context* context, int argc, sqlite3_value** argv)
^
_Nonnull
./cqlrt_common.c:4298:81: error: pointer is missing a …
```
> Fix sqlite callback signature

- sources/playground/play.sh
When the compiler dependency was not satisfied, executing the command `./play.sh build-cql-compiler` was listing the dependencies instead of building cql
> Fix `./play.sh build-cql-compiler`

- CQL_Guide/x4.md
- sources/cg_c.c
- sources/cg_lua.c
- sources/sem.c
- sources/test/cg_test.sql
- sources/test/cg_test_c.c.ref
- sources/test/cg_test_c_with_header.c.ref
- sources/test/cg_test_c_with_namespace.c.ref
- sources/test/cg_test_lua.lua.ref
- sources/test/cg_test_lua.sql
- sources/test/run_test.sql
- sources/test/sem_test.err.ref
- sources/test/sem_test.out.ref
- sources/test/sem_test.sql
In a `CASE` statement each `WHEN` expression must not be a constant NULL. For example:
```sql
declare hex text;
set hex := case color
when NULL    then "#FFFFFF" -- error
when "red"   then "#FF0000"
when "green" then "#00FF00"
when "blue"  then "#0000FF"
else "#000000"
end;
```
When the case expression `color` evaluates to NULL, it does not match with an expression that evaluates to NULL.
Consequently, the CASE statement will default to the ELSE clause, provided it is defined.
TODO:
> Feature: Introduce new Error: CQL0501 WHEN expression must not be a constant NULL but can be of a nullable type

- sources/playground/utils/timer.c
I went very deep but it was a simple include conflicting with objc runtime...
> Fix Playground — benchmark.sql example — Fix objc runtime: cqlrt.h was included in time.c

- sources/playground/README.md
- sources/playground/play.sh
It creates an sqlite database from the sql_schema.
Fun sad fact: the sqlite output cannot be used in a CQL app because there is a table called `column` which is part of the grammar so there is a conflict.
> Playground — Introduce cql_sqlite_schema output

- sources/cqlrt_common.c
```
In file included from cqlrt.c:481:
./cqlrt_common.c:3887:67: error: nullability specifier '_Nullable' conflicts with existing specifier '_Nonnull' [-Werror,-Wnullability]
int32_t get_object_cql_string_list_count(cql_object_ref _Nullable list) {
^
./cqlrt_common.h:421:77: note: previous declaration is here
CQL_EXPORT int32_t get_object_cql_string_list_count(cql_object_ref _Nonnull list);
```
> Fix cqlrt_common get_object_cql_string_list_count signature

- docs/user_guide/14_shared_fragments.md
- docs/user_guide/appendices/04_error_codes.md
- sources/sem.c
- sources/test/sem_test.err.ref
- sources/test/sem_test.out.ref
- sources/test/sem_test.sql
Make it possible to write a shared fragment that doesn't have an else clause like this:
```sql
[[shared_fragment]]
proc my_frag(cond_ bool not null)
begin
if cond_ then
select 1 a, 2 b, 3 c;
end if;
end;
```
This simply rewrites into:
```sql
[[shared_fragment]]
proc my_frag(cond_ bool not null)
begin
if cond_ then
select 1 a, 2 b, 3 c;
else
SELECT NOTHING;
end if;
end;
```
> Allow conditional shared fragments to be written without an ELSE clause

- sources/cg_c.c
- sources/cg_common.h
- sources/cg_lua.c
- sources/gen_sql.c
- sources/sem.h
- sources/test/cg_test.sql
- sources/test/cg_test_c.c.ref
- sources/test/cg_test_c.h.ref
- sources/test/cg_test_c_with_header.c.ref
- sources/test/cg_test_c_with_header.h.ref
- sources/test/cg_test_c_with_namespace.c.ref
- sources/test/cg_test_c_with_namespace.h.ref
- sources/test/cg_test_exports.out.ref
- sources/test/cg_test_lua.lua.ref
- sources/test/cg_test_lua.sql
- sources/test/cg_test_objc.out.ref
The `_ns_` wrapper seems to have been added to avoid generating two different generated sql strings for the same fragment (with and without column aliases). But in practice the cost of creating an extra cte wrapper around a subquery can be quite high (in memory usage and runtime), so it's probably worth the tradeoff to remove the wrapper for some small overhead in codegen when the same fragment is used both in a WITH and FROM clause.
> Remove the _ns_ wrapper when using shared fragments in a FROM clause

- sources/sem.c
- sources/test/sem_test.err.ref
- sources/test/sem_test.out.ref
- sources/test/sem_test.sql
Fix a bug where you can do this without CQL raising an error:
```
select a_shared_frag.* from (call a_shared_frag(1, 2));
```
This shouldn't be allowed because `a_shared_frag` hasn't actually been defined as an alias.
> Using fragment as a nested subquery doesn't automatically define an alias

- sources/cg_c.c
- sources/cg_lua.c
- sources/charbuf.c
- sources/charbuf.h
- sources/gen_sql.c
- sources/gen_sql.h
- sources/test/cg_test.sql
- sources/test/cg_test_c.c.ref
- sources/test/cg_test_c_with_header.c.ref
- sources/test/cg_test_c_with_namespace.c.ref
- sources/test/cg_test_json_schema.out.ref
- sources/test/cg_test_json_schema.sql
- sources/test/cg_test_lua.lua.ref
- sources/test/cg_test_lua.sql
- sources/test/cg_test_query_plan.out.ref
- sources/test/cg_test_query_plan.sql
- sources/test/cg_test_test_helpers.out.ref
- sources/test/macro_test.out.ref
- sources/test/macro_test.sql
- sources/test/sem_test.err.ref
- sources/test/sem_test.out.ref
- sources/test/sem_test.sql
- sources/test/sem_test_migrate.out.ref
- sources/test/test.out.ref
- sources/test/test.sql
- sources/test/test_exp.out.ref
The code in `gen_sql.c` which echos the AST back is the oldest except for `cql.y` and `ast.c`. As such many of the features like character buffers didn't even exist when it was first written and were sort of retrofitted.  When writing to stdout directly there was little we could do to get enough context to properly indent so only a modest effort was made to do something reasonable.
I've made a pass over some of the most popular constructs to try to better.  As a result insert, update, and select statements are hugely improved.  Some day we can turn it into a CQL auto-formatter but for now at least the echo is more readable.
Unfortunately this broke a lot of tests.  But fortunately having to look at the all the failures found lots of bugs and so my confidence that I haven't broken anything …
> There were many cases where the CQL echoing could do better layout

- sources/cql-verify/cql-verify.c
- sources/cql-verify/cql-verify.h
- sources/cql-verify/cql-verify.sql
- sources/test.sh
- sources/test/cg_test.sql
- sources/test/cg_test_c_globals.sql
- sources/test/cg_test_c_type_getters.sql
- sources/test/cg_test_json_schema.out.ref
- sources/test/cg_test_json_schema.sql
- sources/test/cg_test_lua.sql
- sources/test/cg_test_query_plan.sql
- sources/test/cg_test_test_helpers.sql
- sources/test/macro_test.sql
- sources/test/schema_version_error.sql
- sources/test/sem_test.sql
- sources/test/sem_test_dev.sql
- sources/test/sem_test_migrate.sql
- sources/test/sem_test_prev.sql
- sources/test/test.sql
The old version of cql-verify supported these sequences:
```
-- + foo       --> match foo anywhere in the test case output
-- +[0-9] foo  --> match foo anywhere, but demand exactly n matches
-- - foo       --> shorthand for +0 foo (demand no matches)
```
Importantly with this pattern:
```
-- + foo
-- + bar
```
It was not the case that `bar` has to come after `foo` even though that is often what authors expected.  
In-order matching is now the law of the land!
The new escape sequences mean:
```
-- match and advance the current match pointer
-- + foo       --> match foo, searching forward from the last match with +
-- these forms do not change the current search position
-- +[0-9] foo  --> match foo anywhere, but demand exactly n matches
-- - foo       --> shorthand for +0 foo (demand no …
```
> Enhance test cases with in-order matching

- sources/cg_c.c
- sources/cql.h
- sources/cql.y
- sources/cqlrt_common.h
- sources/rt_common.c
- sources/test.sh
- sources/test/cg_test.sql
- sources/test/cg_test_c.c.ref
- sources/test/cg_test_c.h.ref
- sources/test/cg_test_c_with_header.c.ref
- sources/test/cg_test_c_with_header.h.ref
- sources/test/cg_test_c_with_namespace.c.ref
- sources/test/cg_test_c_with_namespace.h.ref
- sources/test/cg_test_c_with_type_getters.h.ref
- sources/test/usage.out.ref
Responding to the issue discussed here: https://github.com/ricomariani/CG-SQL-author/discussions/73
It seems like the `--generate_type_getters` option is the best way to go forward.  The alternative is to fatten all result sets which seems far worse.  This way we get to delete code instead of complicating code and we get a more flexible ABI.
The optional path becomes the new default and only option.  I've removed the option entirely and deleted the other code.
> Type getters only -- the "smaller/faster" path doesn't actually work in all cases

- docs/user_guide/appendices/04_error_codes.md
- sources/cql.y
- sources/gen_sql.c
- sources/rewrite.c
- sources/rewrite.h
- sources/sem.c
- sources/test/sem_test.err.ref
- sources/test/sem_test.out.ref
- sources/test/sem_test.sql
- sources/test/test.out.ref
- sources/test/test.sql
- sources/test/test_exp.out.ref
Allow this sugar in update statements (same way as it exists in insert and update cursor statements):
```
update my_table(like some_shape) from arguments;
```
This gets rewritten into a SET update_list behind the scenes. Note that the ordering of `columns_spec` needs to match the shape of the `insert_list` (so `like some_shape` and `arguments` in the above example need to have matching elements in order).
> Allow FROM shape syntax sugar in update statements

- docs/developer_guide/03_c_code_generation.md
- docs/developer_guide/06_schema_management.md
- docs/user_guide/04_procedures_functions_control_flow.md
- docs/user_guide/09_statements_summary_and_error_checking.md
- docs/user_guide/10_schema_management.md
- docs/user_guide/18_pre_processing.md
- docs/user_guide/appendices/06_cql_in_20_minutes.md
- playground/examples/cql_in_20_minutes.sql
- sources/cg_query_plan.c
- sources/cg_schema.c
- sources/cql-verify/cql-verify.c
- sources/cql-verify/cql-verify.h
- sources/cql-verify/cql-verify.sql
- sources/sem.c
- sources/test/cg_test.sql
- sources/test/cg_test_json_schema.out.ref
- sources/test/cg_test_json_schema.sql
- sources/test/cg_test_lua.sql
- sources/test/cg_test_query_plan.out.ref
- sources/test/cg_test_query_plan.sql
- sources/test/cg_test_schema_min_version_upgrade.out.ref
- sources/test/cg_test_schema_partial_upgrade.out.ref
- sources/test/cg_test_schema_upgrade.out.ref
- sources/test/cqltest.h
- sources/test/run_test.sql
- sources/test/sem_test.sql
All of these have been changed to the simpler equivalent notation. For coverage there is one case left in test.sql just to make sure the old way continues to parse.
> remove all uses of begin try end try begin catch end catch

- sources/sem.c
It's used only in sem.c so no need to be global.
> Change from global to static variable.

- docs/user_guide/appendices/04_error_codes.md
- sources/ast.h
- sources/cql.y
- sources/gen_sql.c
- sources/rewrite.c
- sources/rewrite.h
- sources/sem.c
- sources/test/sem_test.err.ref
- sources/test/sem_test.out.ref
- sources/test/sem_test.sql
- sources/test/test.out.ref
- sources/test/test.sql
- sources/test/test_exp.out.ref
The idea is that in this form the type of the arguments becomes part of the rewritten function call.  This can include more than one argument type.
Here is an example that could build a list for you:
```
declare function new_builder() create object<list_builder>;
declare function object_list_builder_int(arg1 object<list_builder>, arg2 int!) object<list_builder>;
declare function object_list_builder_int_int(arg1 object<list_builder>, arg2 int!, arg3 int!) object<list_builder>;
declare function object_list_builder_real(arg1 object<list_builder>, arg2 real!) object<list_builder>;
declare function to_list_object_list_builder(arg1 object<list_builder>) create object<list>;
let list := new_builder():(5):(7.0):(1,2):::to_list();
```
This expands to the much less readable:
```
LET list := …
```
> Adding support for polymorphic (overloads) invocation using pipeline syntax

- scripts/grammar_utils/tree_sitter.py
- sources/ast.c
- sources/ast.h
- sources/cql.h
- sources/cql.l
- sources/cql.y
- sources/gen_sql.c
- sources/test.sh
- sources/test/macro_basic_parse_test.sql
- sources/test/macro_exp_errors.sql
- sources/test/macro_test.err.out.ref
- sources/test/macro_test.out.ref
- sources/test/macro_test.sql
- sources/test/run_test.sql
- sources/test/test.out.ref
- sources/test/test.sql
- sources/test/test_exp.out.ref
- sources/unit_tests.c
The manual grammar I was using for macro parsing in tree-sitter was actually a lot more flexible and cleaner than the one the real code used.  I changed the real code to be on the tree-sitter plan. This let me delete a lot of custom junkola and it for sure simplified the tree-sitter generation because now there is no special case code to generate working tree-sitter grammar from the .y file -- it just works;
This version is a lot more flexible in terms of how @ifdef and @macro can compose.  In particular it's quite good at parsing inert macros and dealing with macros that are unknown.  The tree-sitter grammar was too.
This is a no-op change except for one thing:  select core macro references have to be wrapped in ROWS(foo!).  These are hardly very popular but technically this is a …
> Cleaner macros -- the tree-sitter way

- .github/workflows/CICD.yml
- sources/common/test_helpers.sh
- sources/sqlite3_cql_extension/.gitignore
- sources/sqlite3_cql_extension/README.md
- sources/sqlite3_cql_extension/Sample.sql
- sources/sqlite3_cql_extension/cql_sqlite_extension.c
- sources/sqlite3_cql_extension/cql_sqlite_extension.h
- sources/sqlite3_cql_extension/cqlsqlite3extension.py
- sources/sqlite3_cql_extension/make.sh
- sources/sqlite3_cql_extension/test.out.ref
- sources/sqlite3_cql_extension/test.sh
- sources/sqlite3_cql_extension/test.sql
```sql
proc comprehensive_test(
in in__bool__not_null bool not null,
in in__bool__nullable bool,
in in__real__not_null real not null,
in in__real__nullable real,
in in__integer__not_null integer not null,
in in__integer__nullable integer,
in in__long__not_null long not null,
in in__long__nullable long,
in in__text__not_null text not null,
in in__text__nullable text,
-- in in__object__not_null object not null,
-- in in__object__nullable object,
in in__blob__not_null blob not null,
in in__blob__nullable blob,
inout inout__bool__not_null bool not null,
inout inout__bool__nullable bool,
inout inout__real__not_null real not null,
inout inout__real__nullable real,
inout inout__integer__not_null integer not null,
inout inout__integer__nullable integer,
inout inout__long__not_null long not null, …
```
> Introduce sqlite3_cql_extension codegen

- sources/objc_full/README.md
- sources/objc_full/Sample.sql
- sources/objc_full/clean.sh
- sources/objc_full/cql_objc_full.py
- sources/objc_full/make.sh
- sources/objc_full/my_objc.m
This is a more advanced version of the objective C API wrapper, it is much more similar to the Java and DotNet versions in that it gives you a full API including calls to the procedures using the native types.
It's unfortunate that the API names for idomatic Objective C are massive so you get stuff like
```c
CGSDemoReturnType *result = CGSCreateDemoReturnType(db, args);
```
However, instead of just getting some bridge helpers like you do with the classic objc wrappers (which are still there) this gives you a class for each result set and a class for each procedure that has out arguments.
Many improvements are possible but this is much better starting point than the just the bridge helpers.
There are two major caveats:
* the code is a fork of the java generator so it still has references …
> OBJC full generator

- sources/cql-verify/cql-verify.c
- sources/cql-verify/cql-verify.h
- sources/cql-verify/cql-verify.sql
- sources/cql-verify/cqlhelp.c
- sources/cqlrt.c
- sources/cqlrt.h
- sources/cqlrt_cf/cqlrt_cf.c
- sources/cqlrt_common.c
- sources/cqlrt_common.h
- sources/test/cg_test.sql
- sources/test/cg_test_c.c.ref
- sources/test/cg_test_c.h.ref
- sources/test/cg_test_c_with_header.c.ref
- sources/test/cg_test_c_with_header.h.ref
- sources/test/cg_test_c_with_namespace.c.ref
- sources/test/cg_test_c_with_namespace.h.ref
For historical reasons the various signed/unsigned and integer size conversions warnings did get turned on in `cqlrt.c` and `cqlrt_common.c`.  This PR enables those warnings in a special build and includes fixes for all of the various conversions.
This is all mostly harmless stuff because the things involved are row sizes, row and column counts and so forth.  These numbers are very small.  Still this code is quite a bit cleaner.
The general changes to make all this happen:
* lots of counts and sizes became unsigned
* `bytebuf` `used` and `max` became unsigned
* various binary formats changes to unsigned (e.g. the blob formats for blob storage and backed tables)
* these changes are not breaking as the values were always positive anyway
* most sqlite functions take ints even for sizes and …
> cqlrt and cqlrt_cf had much lower warning settings

- sources/cql.y
- sources/cqlrt.lua
- sources/cqlrt_common.c
- sources/lua_demo/run_test_lua.ref
- sources/sem.c
- sources/test/cg_test_c.c.ref
- sources/test/cg_test_c.h.ref
- sources/test/cg_test_c_globals.c.ref
- sources/test/cg_test_c_globals.h.ref
- sources/test/cg_test_c_with_header.c.ref
- sources/test/cg_test_c_with_header.h.ref
- sources/test/cg_test_c_with_namespace.c.ref
- sources/test/cg_test_c_with_namespace.h.ref
- sources/test/cg_test_c_with_type_getters.c.ref
- sources/test/cg_test_c_with_type_getters.h.ref
- sources/test/cg_test_json_schema.out.ref
- sources/test/cg_test_lua.lua.ref
- sources/test/run_test.sql
- sources/test/sem_test_dev.out.ref
- sources/test/sem_test_migrate.out.ref
- sources/test/sem_test_prev.out.ref
- sources/test/test_ast.out.ref
The idea here is that you might want to put more than one row into a blob.  It's really more like a blob stream actually...
The helpers are:
```
DECLARE FUNC cql_make_blob_stream (list OBJECT<cql_blob_list>!) CREATE BLOB!
DECLARE FUNC cql_blob_stream_count (b BLOB!) INT!;
DECLARE PROC cql_cursor_from_blob_stream (C CURSOR, b BLOB, i INT!) USING TRANSACTION;
```
* use `cql_blob_list` helpers to make a list of blobs to encode
* these blobs should be generated by serializing cursors via blob storage
* use `cql_make_blob_stream` to make the final blob, the "stream"
The final blob has
* a count of embedded blobs
* the offset to the end of each blob
* the data for each blob
Then:
* use `cql_cursor_from_blob_stream` to extract one of the blobs into a cursor
Importantly, such blobs can be nested …
> Adding helper functions to create "blob arrays"

- sources/sem.c
- sources/test/sem_test.err.ref
- sources/test/sem_test.out.ref
- sources/test/sem_test.sql
See https://github.com/ricomariani/CG-SQL-author/issues/169
given 
```
interface an_interface(x int, y int);
interface another_interface(x int, y int, z int);
interface a_base_type (foo object<an_interface>);
[[implements=a_base_type]]
proc my_proc()
begin
cursor C like (foo object<another_interface>);
fetch C from somewhere;
out C;
end;
```
Previously the presence of `<an_interface>` in the required type `a_base_type` was totally ignored.  This is wrong.
Now, if a type kind like `<an_interface>` is specified then the matching column (`foo` in this case) is recursively checked to ensure that `another_interface` has all the columns of `an_interface`.
Note that to facilitate the use of abstract types that are not actually direct rowset shapes  the `set` in `object<foo set>` is ignored, only …
> Recursive interface match when type kind is specified in [[implements=...]

- .github/workflows/CICD.yml
- sources/sqlite3_cql_extension/cqlsqlite3extension.py
https://github.com/ricomariani/CG-SQL-author/issues/185
The CICD was failing because luarocks no longer installs (see issue for root cause).  However, we don't even need Lua or Laurocks for our CICD at this point so I just removed it.  If we ever do need it we'll have to consider how to get this in a stable fashion.
> changing luarocks version to try to avoid CICD failure
